import Link from "next/link";
import { ArrowLeftIcon, ArchiveBoxIcon, BoltIcon } from "@heroicons/react/24/outline";
import { activateEventAction, createEventAction } from "@/app/actions/events";
import { requireAdmin, getAdminEvents } from "@/lib/dal";

export const metadata = { title: "Kelola Edisi" };
export const dynamic = "force-dynamic";

export default async function AdminEventsPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  await requireAdmin();
  const [events, query] = await Promise.all([getAdminEvents(), searchParams]);
  const message = typeof query.success === "string" ? query.success : typeof query.error === "string" ? query.error : null;
  const messageType = typeof query.error === "string" ? "error" : "success";
  return <section className="admin-page section-shell"><div className="dashboard-heading"><div><Link className="back-link" href="/admin"><ArrowLeftIcon />Kembali ke panel admin</Link><span className="eyebrow">EVENT OPERATIONS</span><h1>Kelola edisi.</h1><p>Buat edisi tahunan baru, lalu aktifkan saat masa pendaftaran dimulai.</p></div></div>{message && <div className={`form-alert form-alert-${messageType}`}>{message}</div>}<div className="team-onboarding"><div className="dashboard-card"><div className="card-icon"><ArchiveBoxIcon /></div><h2>Buat edisi baru</h2><p>Edisi dimulai sebagai draft dan memakai enrollment code sendiri.</p><form action={createEventAction} className="stack-form"><label className="field"><span>Nama edisi</span><input name="displayName" required defaultValue="RPL Expo 2027" /></label><label className="field"><span>Slug URL</span><input name="slug" required placeholder="rpl-expo-2027" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" /></label><div className="form-row"><label className="field"><span>Tahun</span><input name="year" type="number" min={2000} max={2200} required defaultValue={new Date().getFullYear() + 1} /></label><label className="field"><span>Lokasi</span><input name="venue" required defaultValue="SMKN 24 Jakarta" /></label></div><label className="field"><span>Tagline</span><input name="tagline" required defaultValue="Code. Create. Inspire." /></label><div className="form-row"><label className="field"><span>Min anggota</span><input name="teamMinSize" type="number" min={1} max={50} required defaultValue={1} /></label><label className="field"><span>Max anggota</span><input name="teamMaxSize" type="number" min={1} max={50} required defaultValue={6} /></label></div><label className="field"><span>Kode enrollment</span><input name="enrollmentCode" required minLength={8} autoComplete="new-password" placeholder="Kode untuk peserta" /></label><button className="button button-primary" type="submit">Buat draft edisi</button></form></div><div className="dashboard-card"><div className="card-icon"><BoltIcon /></div><h2>Daftar edisi</h2><p>Satu edisi aktif melayani halaman utama; edisi selesai tetap tersedia di arsip.</p><div className="edition-list">{events.map((event) => <article className={`edition-row ${event.isActive ? "edition-active" : ""}`} key={event.id}><div><strong>{event.displayName}</strong><span>{event.year} · {event.status} · /editions/{event.slug}</span></div>{event.isActive ? <small>AKTIF</small> : <form action={activateEventAction}><input type="hidden" name="eventId" value={event.id} /><button className="button button-ghost button-compact" type="submit">Aktifkan</button></form>}</article>)}</div></div></div></section>;
}
